In [4]:
import numpy as np
import pandas as pd
population=pd.Series({'California':78983890,'Texas':84368493,'New York':36536986,'Florida':97655373})
print(population)

df1=pd.DataFrame(population,columns=['population'])
print(df1)

df2=pd.DataFrame(np.random.rand(3,2),columns=['foo','bar'],index=['a','b','c'])
print(df2)

df3=pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])
print(df3)

d=[
    {'a':i,'b':2*i}
    for i in range(10)
]
df4=pd.DataFrame(d)xcxxxcxxxccxxxxxxxxxccc
print(df4)

California    78983890
Texas         84368493
New York      36536986
Florida       97655373
dtype: int64
            population
California    78983890
Texas         84368493
New York      36536986
Florida       97655373
        foo       bar
a  0.630794  0.834335
b  0.805093  0.597691
c  0.394278  0.195515
     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0
   a   b
0  0   0
1  1   2
2  2   4
3  3   6
4  4   8
5  5  10
6  6  12
7  7  14
8  8  16
9  9  18

In [5]:
import pandas as pd

s1 = pd.Series([10, 20, 30], index=['A', 'B', 'C'], name='Row_1')
s2 = pd.Series([40, 50, 60], index=['A', 'B', 'C'], name='Row_2')

series_list = [s1, s2]

df = pd.DataFrame(series_list)
print(df)

        A   B   C
Row_1  10  20  30
Row_2  40  50  60

In [6]:
import numpy as np
import pandas as pd

data = np.array([
    (1, 'Banuraj', 85),
    (2, 'Rahul', 90),
    (3, 'Kiran', 78),
    (4, 'Arun', 88)
], dtype=[
    ('ID', 'i4'),
    ('Name', 'U10'),
    ('Marks', 'i4')
])

df = pd.DataFrame(data)

print(df)

   ID     Name  Marks
0   1  Banuraj     85
1   2    Rahul     90
2   3    Kiran     78
3   4     Arun     88

In [9]:
import numpy as np
import pandas as pd

ind=pd.Index([2,3,5,7,11])
print(ind)

print(ind.size,ind.shape,ind.ndim,ind.dtype)


print(ind[1])
print(ind[::2])
print(ind[1:4:2])

indA=pd.Index([1,3,5,7,9])
indB=pd.Index([2,3,5,7,11])

print(indA & indB)
print(indA | indB)
print(indA ^ indB)
print(indA.intersection(indB))

Index([2, 3, 5, 7, 11], dtype='int64')
5 (5,) 1 int64
3
Index([2, 5, 11], dtype='int64')
Index([3, 7], dtype='int64')
Index([0, 3, 5, 7, 9], dtype='int64')
Index([3, 3, 5, 7, 11], dtype='int64')
Index([3, 0, 0, 0, 2], dtype='int64')
Index([3, 5, 7], dtype='int64')

In [14]:
import pandas as pd


s = pd.Series([45, 67, 89, 23, 56])

print("Series:")
print(s)

print("\nValues:")
print(s.values)

print("\nIndex:")
print(s.index)

Series:
0    45
1    67
2    89
3    23
4    56
dtype: int64

Values:
[45 67 89 23 56]

Index:
RangeIndex(start=0, stop=5, step=1)

In [15]:
import pandas as pd

population = pd.Series(
    [20411000, 32941000, 12765000, 11503000, 14974000],
    index=["Mumbai", "Delhi", "Bengaluru", "Chennai", "Kolkata"]
)

print("Population Series:")
print(population)

print("\nPopulation of Bengaluru:")
print(population["Bengaluru"])

print("\nDelhi to Chennai:")
print(population["Delhi":"Chennai"])

Population Series:
Mumbai       20411000
Delhi        32941000
Bengaluru    12765000
Chennai      11503000
Kolkata      14974000
dtype: int64

Population of Bengaluru:
12765000

Delhi to Chennai:
Delhi        32941000
Bengaluru    12765000
Chennai      11503000
dtype: int64

In [1]:
import numpy as np
import pandas as pd

data=pd.Series([1,np.nan,3,None,5],index=['a', 'b', 'c', 'd', 'e'])
print(data)
print(data.isnull())
print(data.notnull())

a    1.0
b    NaN
c    3.0
d    NaN
e    5.0
dtype: float64
a    False
b     True
c    False
d     True
e    False
dtype: bool
a     True
b    False
c     True
d    False
e     True
dtype: bool

In [10]:
import pandas as pd
data1=pd.Series([1,np.nan,3,None,5],index=['a', 'b', 'c', 'd', 'e'])
data2=data1.dropna()
print(data1)
print(data2)

data3=pd.DataFrame([[1,np.nan,2],[2,3,5],[np.nan,4,6]])
print(data3)
print(data3.dropna())
print(data3.dropna(axis='columns'))
print(data3.dropna(axis='columns',how='all'))
print(data3.dropna(axis='rows',thresh=3))

a    1.0
b    NaN
c    3.0
d    NaN
e    5.0
dtype: float64
a    1.0
c    3.0
e    5.0
dtype: float64
     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6
     0    1  2
1  2.0  3.0  5
   2
0  2
1  5
2  6
     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6
     0    1  2
1  2.0  3.0  5

In [12]:
import numpy as np
import pandas as pd

data4 = pd.DataFrame([[1, np.nan, 2], [2, 3, 5], [np.nan, 4, 6]])
print(data4)


print(data4.fillna(0))
print(data4.ffill())
print(data4.bfill())

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6
     0    1  2
0  1.0  0.0  2
1  2.0  3.0  5
2  0.0  4.0  6
     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  2.0  4.0  6
     0    1  2
0  1.0  3.0  2
1  2.0  3.0  5
2  NaN  4.0  6

In [7]:
import pandas as pd

index = [('A', 2010), ('A', 2020), ('A', 2025), ('B', 2010), ('B', 2020), ('B', 2025)]
population = [123, 456, 789, 101, 121, 131]

pop = pd.Series(population)

i = pd.MultiIndex.from_tuples(index)
print(i)

pop = pop.reindex(i)
print(pop)

pop_df = pop.unstack()
print(pop_df)
pop_df.stack()

MultiIndex([('A', 2010),
            ('A', 2020),
            ('A', 2025),
            ('B', 2010),
            ('B', 2020),
            ('B', 2025)],
           )
A  2010   NaN
   2020   NaN
   2025   NaN
B  2010   NaN
   2020   NaN
   2025   NaN
dtype: float64
   2010  2020  2025
A   NaN   NaN   NaN
B   NaN   NaN   NaN

A  2010   NaN
   2020   NaN
   2025   NaN
B  2010   NaN
   2020   NaN
   2025   NaN
dtype: float64

In [8]:
import pandas as pd


states = ['A', 'A', 'A', 'B', 'B', 'B']
years = [2010, 2020, 2025, 2010, 2020, 2025]
population = [123, 456, 789, 101, 121, 131]
i = pd.MultiIndex.from_arrays([states, years], names=['state', 'year'])
print(i)

pop = pd.Series(population, index=i)
print(pop)
pop_df = pop.unstack()
print(pop_df)

MultiIndex([('A', 2010),
            ('A', 2020),
            ('A', 2025),
            ('B', 2010),
            ('B', 2020),
            ('B', 2025)],
           names=['state', 'year'])
state  year
A      2010    123
       2020    456
       2025    789
B      2010    101
       2020    121
       2025    131
dtype: int64
year   2010  2020  2025
state
A       123   456   789
B       101   121   131

In [9]:
import pandas as pd

states = ['A', 'B']
years = [2010, 2020, 2025]
population = [123, 456, 789, 101, 121, 131]

i = pd.MultiIndex.from_product([states, years], names=['state', 'year'])
print(i)

pop = pd.Series(population, index=i)
print(pop)
pop_df = pop.unstack()
print(pop_df)

MultiIndex([('A', 2010),
            ('A', 2020),
            ('A', 2025),
            ('B', 2010),
            ('B', 2020),
            ('B', 2025)],
           names=['state', 'year'])
state  year
A      2010    123
       2020    456
       2025    789
B      2010    101
       2020    121
       2025    131
dtype: int64
year   2010  2020  2025
state
A       123   456   789
B       101   121   131

In [2]:
import pandas as pd

index = [('A', 2010), ('A', 2020), ('A', 2025), ('B', 2010), ('B', 2020), ('B', 2025)]
population = [123, 456, 789, 101, 121, 131]

i = pd.MultiIndex.from_tuples(index, names=["Country", "Year"])
pop = pd.Series(population, index=i)

print(pop)
print(pop['A', 2010])

Country  Year
A        2010    123
         2020    456
         2025    789
B        2010    101
         2020    121
         2025    131
dtype: int64
123

In [3]:
import pandas as pd

products = {
    'Laptop': 999.99,
    'Mouse': 25.50,
    'Keyboard': 45.00
}

price_series = pd.Series(products)

print("Pandas Series:")
print(price_series)

index_as_list = list(price_series.index)
dict_keys = list(products.keys())

is_matching = index_as_list == dict_keys

print("\nSeries Index:", index_as_list)
print("Dictionary Keys:", dict_keys)
print("Do they match?", is_matching)

Pandas Series:
Laptop      999.99
Mouse        25.50
Keyboard     45.00
dtype: float64

Series Index: ['Laptop', 'Mouse', 'Keyboard']
Dictionary Keys: ['Laptop', 'Mouse', 'Keyboard']
Do they match? True

In [5]:
import pandas as pd

area = pd.Series(
    [163696, 268596, 141297, 54556, 65758],
    index=['California', 'Texas', 'Montana', 'New York', 'Florida']
)

population = pd.Series(
    [38980000, 30500000, 1130000, 19570000, 22610000],
    index=['California', 'Texas', 'Montana', 'New York', 'Florida']
)

states = pd.DataFrame({'area': area, 'population': population})

states['density'] = states['population'] / states['area']

print(states)

              area  population     density
California  163696    38980000  238.124328
Texas       268596    30500000  113.553441
Montana     141297     1130000    7.997339
New York     54556    19570000  358.713982
Florida      65758    22610000  343.836491

In [2]:
import pandas as pd

students = [
    {'name': 'Alice', 'marks': 85},
    {'name': 'Bob'},  
    {'name': 'Charlie', 'marks': 92},
    {'name': 'David', 'marks': 78}
]

df = pd.DataFrame(students)
print(df)

      name  marks
0    Alice   85.0
1      Bob    NaN
2  Charlie   92.0
3    David   78.0

In [3]:
import numpy as np
import pandas as pd

random_array = np.random.rand(3, 3)
df = pd.DataFrame(random_array, columns=['A', 'B', 'C'], index=['x', 'y', 'z'])
print(df)

          A         B         C
x  0.876433  0.712763  0.485062
y  0.952014  0.881616  0.330925
z  0.447176  0.684205  0.606704

In [4]:
import pandas as pd

indA = pd.Index([2, 3, 5, 7, 11])
indB = pd.Index([1, 3, 5, 7, 9])

print("Intersection:", indA & indB)
print("Union:", indA | indB)
print("Symmetric Difference:", indA ^ indB)

Intersection: Index([0, 3, 5, 7, 9], dtype='int64')
Union: Index([3, 3, 5, 7, 11], dtype='int64')
Symmetric Difference: Index([3, 0, 0, 0, 2], dtype='int64')

In [5]:
import numpy as np
import pandas as pd

data = pd.Series([1, np.nan, 'hello', None])

mask = data.isnull()
print("Null mask:")
print(mask)

non_null_values = data[~mask]
print("\nNon-null values:")
print(non_null_values)

Null mask:
0    False
1     True
2    False
3     True
dtype: bool

Non-null values:
0        1
2    hello
dtype: object

In [6]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.rand(5, 4), columns=['Col1', 'Col2', 'Col3', 'Col4'])

df.iloc[0, 1] = np.nan
df.iloc[1, 3] = np.nan
df.iloc[3, 0] = np.nan
df.iloc[4, 2] = np.nan

print("DataFrame with missing values:")
print(df)

print("\nMissing values per column:")
print(df.isnull().sum())

DataFrame with missing values:
       Col1      Col2      Col3      Col4
0  0.279797       NaN  0.956862  0.963349
1  0.062832  0.064430  0.145508       NaN
2  0.866264  0.288518  0.173321  0.136151
3       NaN  0.262140  0.244665  0.418880
4  0.660647  0.622852       NaN  0.403664

Missing values per column:
Col1    1
Col2    1
Col3    1
Col4    1
dtype: int64

In [10]:
index=pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])
columns=pd.MultiIndex.from_product([['Bob','Guido','Sue'],['HR','Temp']],names=['name','dept'])
data=np.round(np.random.rand(4,6),1)
health_data=pd.DataFrame(data,index=index,columns=columns)
print(health_data)

name        Bob      Guido       Sue
dept         HR Temp    HR Temp   HR Temp
year visit
2013 1      0.8  0.3   0.9  0.0  0.7  0.9
     2      0.3  0.4   0.6  0.1  0.6  0.8
2014 1      0.8  0.4   0.5  0.9  0.8  0.8
     2      0.6  0.7   0.0  0.9  0.5  0.8

In [17]:
health_data
health_data['Guido','HR']
health_data.iloc[:2, :2]
health_data.loc[:, ('Bob', 'HR')]

idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

index = pd.MultiIndex.from_product([['a', 'c', 'b'],[1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [3]:
pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (2.4.3)
Requirement already satisfied: pandas>=1.2 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns

In [5]:
titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [1]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic.pivot_table('survived', index='sex', columns='class')

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [2]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic.pivot_table('survived', index='sex', columns='class')

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [3]:
titanic.groupby(['class','sex'])['survived'].mean()

class   sex
First   female    0.968085
        male      0.368852
Second  female    0.921053
        male      0.157407
Third   female    0.500000
        male      0.135447
Name: survived, dtype: float64

In [4]:
titanic.groupby(['class','sex'])['age'].mean()

class   sex
First   female    34.611765
        male      41.281386
Second  female    28.722973
        male      30.740707
Third   female    21.750000
        male      26.507589
Name: age, dtype: float64

In [5]:
titanic.groupby(['class','sex'])['age'].min()

class   sex
First   female    2.00
        male      0.92
Second  female    2.00
        male      0.67
Third   female    0.75
        male      0.42
Name: age, dtype: float64